import type { Metadata } from "next";
import { cookies } from "next/headers";
import { MobileDrawer } from "./_components/mobile-drawer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const isStaff = Boolean(cookieStore.get("staff_user_id")?.value);
  const isAdmin = cookieStore.get("admin_auth")?.value === "1";
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><MobileDrawer isStaff={isStaff} isAdmin={isAdmin} />
        {children}</body>
    </html>
  );
}
